In [4]:
from sys import stdin
import numpy as np # linear algebra
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn import metrics

# Load the data
data = pd.read_csv("FlightDelays.csv")

print("The number of rows in the data set is {}.".format(len(data)))
print("The number of features is {}.".format(len(data.columns)))

data.head()

The number of rows in the data set is 450017.
The number of features is 12.

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,AIRLINE_ID,FL_NUM,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,SCHED_DEP_TIME,SCHED_ARR_TIME,DELAY
0,2017,1,1,7,6,19805,1766,11298,12889,1055,1154,0.0
1,2017,1,1,8,7,19805,1766,11298,12889,1055,1154,0.0
2,2017,1,1,1,7,19805,1766,13930,11298,710,948,0.0
3,2017,1,1,2,1,19805,1766,13930,11298,710,948,0.0
4,2017,1,1,3,2,19805,1766,13930,11298,710,948,0.0

In [3]:
# Finding Null Values
data.isnull().sum()

YEAR                    0
QUARTER                 0
MONTH                   0
DAY_OF_MONTH            0
DAY_OF_WEEK             0
AIRLINE_ID              0
FL_NUM                  0
ORIGIN_AIRPORT_ID       0
DEST_AIRPORT_ID         0
SCHED_DEP_TIME          0
SCHED_ARR_TIME          0
DELAY                8541
dtype: int64

In [5]:
new_data = data.dropna(axis=0)#Delete the rows containing missing data
new_data.isnull().sum() #Check to make sure there are no more NaNs

YEAR                 0
QUARTER              0
MONTH                0
DAY_OF_MONTH         0
DAY_OF_WEEK          0
AIRLINE_ID           0
FL_NUM               0
ORIGIN_AIRPORT_ID    0
DEST_AIRPORT_ID      0
SCHED_DEP_TIME       0
SCHED_ARR_TIME       0
DELAY                0
dtype: int64

In [6]:
print("The number of rows in the new data set is {}.".format(len(new_data)))

The number of rows in the new data set is 441476.

In [7]:
#subset the flight that delayed
delay_flight=new_data[new_data.DELAY==1]
print(delay_flight)

        YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  AIRLINE_ID  FL_NUM  \
22      2017        1      1             2            1       19805    1767
24      2017        1      1             4            3       19805    1767
26      2017        1      1             6            5       19805    1767
45      2017        1      1            10            2       19805    1768
64      2017        1      1            29            7       19805    1768
67      2017        1      1             9            1       19805    1769
78      2017        1      1            23            1       19805    1769
80      2017        1      1            25            3       19805    1769
82      2017        1      1            27            5       19805    1769
91      2017        1      1            16            1       19805    1769
98      2017        1      1            25            3       19805    1769
109     2017        1      1             7            6       19805    1769
110     2017        1      1             8            7       19805    1769
111     2017        1      1             9            1       19805    1770
139     2017        1      1             9            1       19805    1770
140     2017        1      1            10            2       19805    1770
149     2017        1      1            20            5       19805    1770
151     2017        1      1            23            1       19805    1770
192     2017        1      1             9            1       19805    1772
195     2017        1      1            12            4       19805    1772
198     2017        1      1            15            7       19805    1772
257     2017        1      1            23            1       19805    1773
261     2017        1      1            27            5       19805    1773
268     2017        1      1             5            4       19805    1773
282     2017        1      1             5            4       19805    1774
293     2017        1      1            20            5       19805    1774
295     2017        1      1            22            7       19805    1774
303     2017        1      1             2            1       19805    1774
314     2017        1      1             3            2       19805    1775
317     2017        1      1             6            5       19805    1775
...      ...      ...    ...           ...          ...         ...     ...
449796  2017        1      1             6            5       19805    1760
449801  2017        1      1            12            4       19805    1760
449821  2017        1      1             1            7       19805    1761
449828  2017        1      1             8            7       19805    1761
449830  2017        1      1            10            2       19805    1761
449842  2017        1      1            22            7       19805    1761
449843  2017        1      1            23            1       19805    1761
449844  2017        1      1            24            2       19805    1761
449869  2017        1      1             9            1       19805    1762
449897  2017        1      1             7            6       19805    1763
449899  2017        1      1             9            1       19805    1763
449904  2017        1      1            14            6       19805    1763
449908  2017        1      1            19            4       19805    1763
449922  2017        1      1             4            3       19805    1763
449924  2017        1      1             6            5       19805    1763
449925  2017        1      1             7            6       19805    1763
449927  2017        1      1             9            1       19805    1763
449932  2017        1      1            14            6       19805    1763
449933  2017        1      1            15            7       19805    1763
449937  2017        1      1            19            4       19805    1763
449942  2017        1      1            24            2       19805    1763
449943  2017        1      1            25            3       19805    1763
449966  2017        1      1            17            2       19805    1764
449985  2017        1      1             1            7       19805    1765
449986  2017        1      1             7            6       19805    1765
449988  2017        1      1             9            1       19805    1766
449992  2017        1      1            13            5       19805    1766
450012  2017        1      1             2            1       19805    1766
450014  2017        1      1             4            3       19805    1766
450015  2017        1      1             5            4       19805    1766

        ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  SCHED_DEP_TIME  SCHED_ARR_TIME  \
22                  12889            11298            1235            1718
24                  12889            11298            1235            1718
26                  12889            11298            1235            1718
45                  11278            13303            1015            1313
64                  11278            13303            1015            1313
67                  11057            15016            1300            1356
78                  11057            15016            1300            1356
80                  11057            15016            1300            1356
82                  11057            15016            1300            1356
91                  13495            11057             920            1213
98                  13495            11057             920            1213
109                 15304            13303             730             833
110                 15304            13303             730             833
111                 10693            11057             600             825
139                 11057            13931             916            1019
140                 11057            13931             916            1019
149                 11057            13931             916            1019
151                 11057            13931             916            1019
192                 11057            11298             925            1129
195                 11057            11298             925            1129
198                 11057            11298             925            1129
257                 10721            14100            1500            1641
261                 10721            14100            1500            1641
268                 13204            14100             815            1040
282                 11057            11433            2220               6
293                 14107            11618            2250             527
295                 14107            11618            2250             527
303                 15096            11057            1908            2124
314                 11057            11298            1615            1815
317                 11057            11298            1615            1815
...                   ...              ...             ...             ...
449796              11292            11057             810            1328
449801              11292            11057             810            1323
449821              11278            15304            1800            2035
449828              11278            15304            1800            2035
449830              11278            15304            1801            2033
449842              11278            15304            1759            2034
449843              11278            15304            1801            2033
449844              11278            15304            1801            2033
449869              11057            14492             940            1039
449897              11298            14679             700             811
449899              11298            14679             700             808
449904              11298            14679             700             808
449908              11298            14679             700             808
449922              14679            11298             903            1357
449924              14679            11298             903            1357
449925              14679            11298             903            1357
449927              14679            11298             858            1356
449932              14679            11298             858            1356
449933              14679            11298             847            1345
449937              14679            11298            1200            1653
449942              14679            11298             858            1356
449943              14679            11298             858            1356
449966              11697            11278             815            1044
449985              15024            14100            1330            1637
449986              15024            14100            1330            1639
449988              11278            11298             645             922
449992              11278            11298             645             922
450012              11298            12889            1055            1154
450014              11298            12889            1055            1154
450015              11298            12889            1055            1154

        DELAY
22        1.0
24        1.0
26        1.0
45        1.0
64        1.0
67        1.0
78        1.0
80        1.0
82        1.0
91        1.0
98        1.0
109       1.0
110       1.0
111       1.0
139       1.0
140       1.0
149       1.0
151       1.0
192       1.0
195       1.0
198       1.0
257       1.0
261       1.0
268       1.0
282       1.0
293       1.0
295       1.0
303       1.0
314       1.0
317       1.0
...       ...
449796    1.0
449801    1.0
449821    1.0
449828    1.0
449830    1.0
449842    1.0
449843    1.0
449844    1.0
449869    1.0
449897    1.0
449899    1.0
449904    1.0
449908    1.0
449922    1.0
449924    1.0
449925    1.0
449927    1.0
449932    1.0
449933    1.0
449937    1.0
449942    1.0
449943    1.0
449966    1.0
449985    1.0
449986    1.0
449988    1.0
449992    1.0
450012    1.0
450014    1.0
450015    1.0

[93072 rows x 12 columns]

In [15]:
#exploring most five airport delay
most5_Airport_delay=delay_flight.groupby('ORIGIN_AIRPORT_ID').DELAY.sum().nlargest(5)
print(most5_Airport_delay)

ORIGIN_AIRPORT_ID
10397    6176.0
12892    5453.0
13930    4202.0
11292    4179.0
14771    3831.0
Name: DELAY, dtype: float64

In [10]:
#cleaning data keeping only most five airport delay 
data_5most_airport=new_data.loc[new_data['ORIGIN_AIRPORT_ID'].isin(['10397', '12892', '13930','11292','14771'])] 
print(data_5most_airport)

        YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  AIRLINE_ID  FL_NUM  \
2       2017        1      1             1            7       19805    1766
3       2017        1      1             2            1       19805    1766
4       2017        1      1             3            2       19805    1766
5       2017        1      1             4            3       19805    1766
6       2017        1      1             5            4       19805    1766
7       2017        1      1             6            5       19805    1766
8       2017        1      1             7            6       19805    1766
9       2017        1      1             8            7       19805    1766
595     2017        1      1             1            7       19805    1783
596     2017        1      1             2            1       19805    1783
597     2017        1      1             3            2       19805    1783
598     2017        1      1             4            3       19805    1783
599     2017        1      1             5            4       19805    1783
600     2017        1      1             6            5       19805    1783
601     2017        1      1             7            6       19805    1783
602     2017        1      1             8            7       19805    1783
626     2017        1      1             9            1       19805    1783
628     2017        1      1            11            3       19805    1783
629     2017        1      1            12            4       19805    1783
630     2017        1      1            13            5       19805    1783
631     2017        1      1            14            6       19805    1783
632     2017        1      1            15            7       19805    1783
634     2017        1      1            17            2       19805    1783
635     2017        1      1            18            3       19805    1783
636     2017        1      1            19            4       19805    1783
637     2017        1      1            20            5       19805    1783
638     2017        1      1            21            6       19805    1783
639     2017        1      1            22            7       19805    1783
640     2017        1      1            23            1       19805    1783
641     2017        1      1            24            2       19805    1783
...      ...      ...    ...           ...          ...         ...     ...
449697  2017        1      1            28            6       19805    1757
449791  2017        1      1             1            7       19805    1760
449792  2017        1      1             2            1       19805    1760
449793  2017        1      1             3            2       19805    1760
449794  2017        1      1             4            3       19805    1760
449796  2017        1      1             6            5       19805    1760
449797  2017        1      1             8            7       19805    1760
449798  2017        1      1             9            1       19805    1760
449799  2017        1      1            10            2       19805    1760
449800  2017        1      1            11            3       19805    1760
449801  2017        1      1            12            4       19805    1760
449802  2017        1      1            13            5       19805    1760
449803  2017        1      1            14            6       19805    1760
449804  2017        1      1            15            7       19805    1760
449805  2017        1      1            16            1       19805    1760
449806  2017        1      1            17            2       19805    1760
449807  2017        1      1            18            3       19805    1760
449808  2017        1      1            19            4       19805    1760
449809  2017        1      1            20            5       19805    1760
449810  2017        1      1            21            6       19805    1760
449811  2017        1      1            22            7       19805    1760
449812  2017        1      1            23            1       19805    1760
449813  2017        1      1            24            2       19805    1760
449814  2017        1      1            25            3       19805    1760
449815  2017        1      1            26            4       19805    1760
449816  2017        1      1            27            5       19805    1760
449817  2017        1      1            28            6       19805    1760
449818  2017        1      1            29            7       19805    1760
449819  2017        1      1            30            1       19805    1760
449820  2017        1      1            31            2       19805    1760

        ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  SCHED_DEP_TIME  SCHED_ARR_TIME  \
2                   13930            11298             710             948
3                   13930            11298             710             948
4                   13930            11298             710             948
5                   13930            11298             710             948
6                   13930            11298             710             948
7                   13930            11298             710             948
8                   13930            11298             710             948
9                   13930            11298             710             948
595                 12892            11057            1147            1925
596                 12892            11057            1147            1925
597                 12892            11057            1147            1925
598                 12892            11057            1147            1925
599                 12892            11057            1147            1925
600                 12892            11057            1147            1925
601                 12892            11057            1147            1925
602                 12892            11057            1147            1925
626                 14771            14107             905            1209
628                 14771            14107             905            1209
629                 14771            14107             905            1209
630                 14771            14107             905            1209
631                 14771            14107             905            1209
632                 14771            14107             905            1209
634                 14771            14107             905            1209
635                 14771            14107             905            1209
636                 14771            14107             905            1209
637                 14771            14107             905            1209
638                 14771            14107             905            1209
639                 14771            14107             905            1209
640                 14771            14107             905            1209
641                 14771            14107             905            1209
...                   ...              ...             ...             ...
449697              10397            11057            1229            1345
449791              11292            11057             810            1328
449792              11292            11057             810            1328
449793              11292            11057             810            1328
449794              11292            11057             810            1328
449796              11292            11057             810            1328
449797              11292            11057             810            1328
449798              11292            11057             810            1323
449799              11292            11057             810            1323
449800              11292            11057             810            1323
449801              11292            11057             810            1323
449802              11292            11057             810            1323
449803              11292            11057             810            1323
449804              11292            11057             810            1323
449805              11292            11057             810            1323
449806              11292            11057             810            1323
449807              11292            11057             810            1323
449808              11292            11057             810            1323
449809              11292            11057             810            1323
449810              11292            11057             810            1323
449811              11292            11057             810            1323
449812              11292            11057             810            1323
449813              11292            11057             810            1323
449814              11292            11057             810            1323
449815              11292            11057             810            1323
449816              11292            11057             810            1323
449817              11292            11057             810            1323
449818              11292            11057             810            1323
449819              11292            11057             810            1323
449820              11292            11057             810            1323

        DELAY
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0
595       0.0
596       1.0
597       0.0
598       1.0
599       1.0
600       1.0
601       0.0
602       0.0
626       1.0
628       1.0
629       0.0
630       0.0
631       0.0
632       0.0
634       0.0
635       0.0
636       0.0
637       1.0
638       0.0
639       0.0
640       0.0
641       0.0
...       ...
449697    0.0
449791    0.0
449792    1.0
449793    0.0
449794    0.0
449796    1.0
449797    0.0
449798    0.0
449799    0.0
449800    0.0
449801    1.0
449802    0.0
449803    0.0
449804    0.0
449805    0.0
449806    0.0
449807    0.0
449808    0.0
449809    0.0
449810    0.0
449811    0.0
449812    0.0
449813    0.0
449814    0.0
449815    0.0
449816    0.0
449817    0.0
449818    0.0
449819    0.0
449820    0.0

[94627 rows x 12 columns]

In [11]:
data=data_5most_airport

In [12]:
print("The number of rows in the new data set is {}.".format(len(data)))

The number of rows in the new data set is 94627.

In [13]:
data.AIRLINE_ID.value_counts()

19790    23066
19977    15815
19393    13593
20304    13301
19805    10930
20366     7097
21171     2989
20416     2436
20436     2425
19930     1504
20409     1274
19690      197
Name: AIRLINE_ID, dtype: int64

In [14]:
data.ORIGIN_AIRPORT_ID.value_counts()

10397    29544
13930    18483
12892    17058
11292    16761
14771    12781
Name: ORIGIN_AIRPORT_ID, dtype: int64

In [15]:
data.DEST_AIRPORT_ID.value_counts()

12889    2990
12892    2950
14771    2492
11298    2491
14107    2426
14747    2359
13930    2214
12478    2079
11292    2013
11618    2003
13487    1940
14869    1930
13204    1826
10397    1712
12266    1711
10721    1694
12953    1660
14679    1595
14100    1438
11057    1390
13303    1383
11433    1369
11697    1348
14057    1218
12264    1217
11278    1213
15304    1037
10423    1036
15016     977
10821     967
         ...
11577      55
14711      55
11471      55
14543      54
14006      54
11617      53
10434      53
12255      49
12519      49
12888      48
11982      44
13344      44
14794      34
10627      34
12156      31
14633      29
13486      24
11413      19
12402      19
13964      17
15027      17
13388      16
14457      15
15356      14
14082      13
11122       6
12896       6
12389       6
13127       1
11447       1
Name: DEST_AIRPORT_ID, Length: 217, dtype: int64

In [16]:
pd.get_dummies(data, columns=['AIRLINE_ID', 'ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID'], drop_first=True)

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_NUM,SCHED_DEP_TIME,SCHED_ARR_TIME,DELAY,AIRLINE_ID_19690,...,DEST_AIRPORT_ID_15304,DEST_AIRPORT_ID_15323,DEST_AIRPORT_ID_15356,DEST_AIRPORT_ID_15370,DEST_AIRPORT_ID_15376,DEST_AIRPORT_ID_15380,DEST_AIRPORT_ID_15412,DEST_AIRPORT_ID_15607,DEST_AIRPORT_ID_15624,DEST_AIRPORT_ID_15919
2,2017,1,1,1,7,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017,1,1,2,1,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,2017,1,1,3,2,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
5,2017,1,1,4,3,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
6,2017,1,1,5,4,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
7,2017,1,1,6,5,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
8,2017,1,1,7,6,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9,2017,1,1,8,7,1766,710,948,0.0,0,...,0,0,0,0,0,0,0,0,0,0
595,2017,1,1,1,7,1783,1147,1925,0.0,0,...,0,0,0,0,0,0,0,0,0,0
596,2017,1,1,2,1,1783,1147,1925,1.0,0,...,0,0,0,0,0,0,0,0,0,0
597,2017,1,1,3,2,1783,1147,1925,0.0,0,...,0,0,0,0,0,0,0,0,0,0
598,2017,1,1,4,3,1783,1147,1925,1.0,0,...,0,0,0,0,0,0,0,0,0,0
599,2017,1,1,5,4,1783,1147,1925,1.0,0,...,0,0,0,0,0,0,0,0,0,0
600,2017,1,1,6,5,1783,1147,1925,1.0,0,...,0,0,0,0,0,0,0,0,0,0
601,2017,1,1,7,6,1783,1147,1925,0.0,0,...,0,0,0,0,0,0,0,0,0,0
602,2017,1,1,8,7,1783,1147,1925,0.0,0,...,0,0,0,0,0,0,0,0,0,0
626,2017,1,1,9,1,1783,905,1209,1.0,0,...,0,0,0,0,0,0,0,0,0,0
628,2017,1,1,11,3,1783,905,1209,1.0,0,...,0,0,0,0,0,0,0,0,0,0
629,2017,1,1,12,4,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
630,2017,1,1,13,5,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
631,2017,1,1,14,6,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
632,2017,1,1,15,7,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
634,2017,1,1,17,2,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
635,2017,1,1,18,3,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
636,2017,1,1,19,4,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
637,2017,1,1,20,5,1783,905,1209,1.0,0,...,0,0,0,0,0,0,0,0,0,0
638,2017,1,1,21,6,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
639,2017,1,1,22,7,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
640,2017,1,1,23,1,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
641,2017,1,1,24,2,1783,905,1209,0.0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449697,2017,1,1,28,6,1757,1229,1345,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449791,2017,1,1,1,7,1760,810,1328,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449792,2017,1,1,2,1,1760,810,1328,1.0,0,...,0,0,0,0,0,0,0,0,0,0
449793,2017,1,1,3,2,1760,810,1328,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449794,2017,1,1,4,3,1760,810,1328,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449796,2017,1,1,6,5,1760,810,1328,1.0,0,...,0,0,0,0,0,0,0,0,0,0
449797,2017,1,1,8,7,1760,810,1328,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449798,2017,1,1,9,1,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449799,2017,1,1,10,2,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449800,2017,1,1,11,3,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449801,2017,1,1,12,4,1760,810,1323,1.0,0,...,0,0,0,0,0,0,0,0,0,0
449802,2017,1,1,13,5,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449803,2017,1,1,14,6,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449804,2017,1,1,15,7,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449805,2017,1,1,16,1,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449806,2017,1,1,17,2,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449807,2017,1,1,18,3,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449808,2017,1,1,19,4,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449809,2017,1,1,20,5,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449810,2017,1,1,21,6,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449811,2017,1,1,22,7,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449812,2017,1,1,23,1,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449813,2017,1,1,24,2,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449814,2017,1,1,25,3,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449815,2017,1,1,26,4,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449816,2017,1,1,27,5,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449817,2017,1,1,28,6,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449818,2017,1,1,29,7,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449819,2017,1,1,30,1,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0
449820,2017,1,1,31,2,1760,810,1323,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
# Setting the train set,test set, and validation set
x= new_data.iloc[:,0:11]
y= new_data['DELAY']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2, random_state = 1)
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size=.25, random_state = 1)

In [28]:
x_train.shape

(264885, 11)

In [29]:
x_test.shape

(88296, 11)

In [30]:
x_val.shape

(88295, 11)